import { GoogleGenAI } from "@google/genai";
import { AiProvider } from "../types";

const SUPABASE_INSTRUCTIONS = `
**Supabase Backend Instructions:**
If the user requests a feature that requires a database (e.g., saving data, user accounts, a blog), you MUST implement it using the Supabase JavaScript client.
1.  **Include the Supabase client library** from its CDN in the \`<head>\`: \`<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>\`.
2.  **Initialize the client** at the beginning of your main \`<script>\` tag using these EXACT placeholders:
    \`\`\`javascript
    const SUPABASE_URL = '%%SUPABASE_URL%%';
    const SUPABASE_ANON_KEY = '%%SUPABASE_ANON_KEY%%';
    const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    \`\`\`
3.  Implement the requested functionality using the initialized \`supabase\` client object (e.g., \`supabase.from('todos').select('*')\`).
4.  If the user is asking for a feature like this for the first time, you must also define the necessary database table schema in a comment block at the top of the \`<script>\` tag, explaining what SQL to run in their Supabase project. For example:
    \`\`\`javascript
    /*
      Supabase Table Schema for this app:
      
      CREATE TABLE todos (
        id bigint generated by default as identity primary key,
        task text,
        is_complete boolean default false,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    */
    \`\`\`
`;

const BASE_SYSTEM_PROMPT = `
You are an expert web developer specializing in creating fully functional and interactive single-file web applications using HTML, CSS, and JavaScript.
Your task is to generate the complete code for an application based on the user's request.
${SUPABASE_INSTRUCTIONS}
Please adhere to the following strict requirements:
1.  **Single File Output:** Generate a single, self-contained \`index.html\` file.
2.  **Inline Everything:**
    -   All CSS must be included within a \`<style>\` tag in the \`<head>\`.
    -   All JavaScript must be included within a \`<script>\` tag right before the closing \`</body>\` tag.
    -   Do not use any external CSS or JS files.
3.  **Functionality First:** The generated JavaScript should be robust and make the application as interactive and functional as requested. For example, if a user asks for a "todo list app", it should have working functionality to add, remove, and mark todos as complete. For extra credit, use \`localStorage\` to persist data, unless a database is requested.
4.  **Modern & Responsive:** The application must be modern, aesthetically pleasing, and fully responsive. Use modern CSS features like Flexbox or Grid.
5.  **Code Only:** Your entire response must be ONLY the HTML code for the application, enclosed in a single markdown code block like this:
    \`\`\`html
    <!DOCTYPE html>
    <html>
    ...
    </html>
    \`\`\`
    Do NOT include any explanations, introductions, or closing remarks outside of the code block.
`;

const MODIFY_SYSTEM_PROMPT = `
You are an expert web developer. Your task is to modify the provided HTML, CSS, and JavaScript code based on the user's request, focusing on adding or improving functionality.
${SUPABASE_INSTRUCTIONS}
Please adhere to these strict requirements:
1.  **Modify, Don't Replace:** Intelligently modify the existing code to incorporate the user's request. Focus on enhancing functionality and interactivity. Do not start from scratch unless the request is a complete overhaul.
2.  **Maintain Structure:** Preserve the single-file, inline-everything (CSS in \`<style>\`, JS in \`<script>\`) structure.
3.  **Robust JavaScript:** Ensure any new or modified JavaScript is well-written, functional, and integrated with the existing code.
4.  **Code Only:** Your entire response must be ONLY the complete, updated HTML code for the website, enclosed in a single markdown code block. Do NOT include explanations.
`;

function getFullPrompt(prompt: string, currentCode?: string): { systemPrompt: string; userMessage: string } {
    const systemPrompt = currentCode ? MODIFY_SYSTEM_PROMPT : BASE_SYSTEM_PROMPT;
    const userMessage = currentCode ?
        `Here is the current code of the single-file web application:\n\`\`\`html\n${currentCode}\n\`\`\`\n\nThe user wants to make the following change: "${prompt}"` :
        `The user's request is: "${prompt}"`;
    return { systemPrompt, userMessage };
}

function extractHtmlCode(responseText: string): string {
    const match = responseText.match(/```html\n([\s\S]*?)\n```/);
    if (match && match[1]) {
        return match[1].trim();
    }
    if (responseText.trim().startsWith('<!DOCTYPE html>')) {
        return responseText.trim();
    }
    const htmlStartIndex = responseText.indexOf('<!DOCTYPE html>');
    if (htmlStartIndex !== -1) {
        return responseText.substring(htmlStartIndex).trim();
    }
    return responseText.trim();
}

async function generateWithGemini(prompt: string, apiKey: string, currentCode?: string): Promise<string> {
    const ai = new GoogleGenAI({ apiKey });
    const { systemPrompt, userMessage } = getFullPrompt(prompt, currentCode);
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-pro',
        contents: [{
            role: 'user',
            parts: [{ text: userMessage }]
        }],
        config: {
            systemInstruction: systemPrompt,
        }
    });

    return extractHtmlCode(response.text);
}

async function generateWithOpenAI(prompt: string, apiKey: string, currentCode?: string): Promise<string> {
    const { systemPrompt, userMessage } = getFullPrompt(prompt, currentCode);
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
            model: 'gpt-4o',
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userMessage }
            ],
            temperature: 0.7,
        })
    });

    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`OpenAI API error: ${errorData.error.message}`);
    }

    const data = await response.json();
    return extractHtmlCode(data.choices[0].message.content);
}

async function generateWithAnthropic(prompt: string, apiKey: string, currentCode?: string): Promise<string> {
    const { systemPrompt, userMessage } = getFullPrompt(prompt, currentCode);
    const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': apiKey,
            'anthropic-version': '2023-06-01'
        },
        body: JSON.stringify({
            model: 'claude-3-haiku-20240307',
            system: systemPrompt,
            messages: [{ role: 'user', content: userMessage }],
            max_tokens: 4096,
            temperature: 0.7,
        })
    });

    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`Anthropic API error: ${errorData.error.message}`);
    }

    const data = await response.json();
    return extractHtmlCode(data.content[0].text);
}


async function generateWithOpenRouter(prompt: string, apiKey: string, currentCode?: string): Promise<string> {
    const { systemPrompt, userMessage } = getFullPrompt(prompt, currentCode);
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": "https://gotidea.vercel.app",
            "X-Title": "Got Idea"
        },
        body: JSON.stringify({
            model: "anthropic/claude-3-haiku", // A fast and capable default model
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userMessage }
            ],
        })
    });
    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`OpenRouter API error: ${errorData.error.message}`);
    }

    const data = await response.json();
    return extractHtmlCode(data.choices[0].message.content);
}


export async function generateWebsiteCode(
    prompt: string, 
    provider: AiProvider, 
    apiKey: string, 
    currentCode?: string,
    supabaseUrl?: string | null,
    supabaseAnonKey?: string | null
): Promise<string> {
  if (!apiKey) {
    throw new Error("API key is not set for the selected provider.");
  }

  try {
    let code: string;
    switch (provider) {
        case 'gemini':
            code = await generateWithGemini(prompt, apiKey, currentCode);
            break;
        case 'openai':
            code = await generateWithOpenAI(prompt, apiKey, currentCode);
            break;
        case 'anthropic':
            code = await generateWithAnthropic(prompt, apiKey, currentCode);
            break;
        case 'openrouter':
            code = await generateWithOpenRouter(prompt, apiKey, currentCode);
            break;
        default:
            throw new Error(`Unsupported AI provider: ${provider}`);
    }

    // Replace Supabase placeholders if credentials are provided
    if (supabaseUrl && supabaseAnonKey) {
        code = code.replace(/%%SUPABASE_URL%%/g, supabaseUrl);
        code = code.replace(/%%SUPABASE_ANON_KEY%%/g, supabaseAnonKey);
    } else if (code.includes('%%SUPABASE_URL%%') || code.includes('%%SUPABASE_ANON_KEY%%')) {
        const warningComment = `<!-- 
  WARNING: This website requires a Supabase backend to function correctly. 
  Please go to the "Settings" page in Got Idea, add your Supabase URL and Anon Key 
  for the "Generated App Backend", and then regenerate or update the website.
-->`;
        code = warningComment + '\n' + code;
    }

    return code;

  } catch (error) {
    console.error(`Error generating website code with ${provider}:`, error);
    if (error instanceof Error) {
        return Promise.reject(new Error(`Failed to generate code: ${error.message}`));
    }
    return Promise.reject(new Error("An unknown error occurred while generating code."));
  }
}